---
# Add your how-to and where-to messages below

vote-hw: "true"
message-how: "Add your how to vote message "
message-where: "Add your where to vote message"


# Set vote to true if you want a message to appear whenever a player types 'vote'

vote: "false"
message-vote: "Add your vote message"
...
